language: java

branches:
  only:
  - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install --only-upgrade -y oracle-java8-installer

jdk:
  - oraclejdk8

after_success:
  - mvn clean test jacoco:report coveralls:jacoco
  - mvn checkstyle:check

notifications:
  email: false

